### ISSUE TITLE
fused_autodoc not working on openmdao 0.10.2

### ISSUE THREAD

**Issue by dykesk** [FUSED-Wind/fusedwind#6]
the fused_autodoc functionality just added appears to work fine on openmdao 0.9.7 but is crashing on openmdao 0.10.2

(I haven't seen this myself so I don't have the error code but our grad student here ran into it - i'll try to install 0.10.2 and check it out later)

**Comment by fzahle** [comment]
I've reactivated the fused_autodoc call and it seems to work ok and I fixed a warning  when building the docs related to the Notes section. 28 warnings to go which are all "Field list ends without a blank line; unexpected unindent".

closing this issue.

**Comment by piredtu** [comment]
I still have some bugs:

![screenshot 2015-01-09 15 03 50](https://cloud.githubusercontent.com/assets/2746159/5680673/cc5824dc-9810-11e4-8f62-f09de97d11c2.png)

**Comment by fzahle** [comment]
its an issue for classes that implement multiple interfaces, which I haven't used so far, so never had that issue. I can't really figure out all the dark magic you've used for these decorator, so haven't been able to fix it. Could you take a look at it?

quick question, why does AEPSingleWindRose implement both BaseAEPModel *and* AEPWindRose? AEPWindRose is listed as implementing BaseAEPModel, so isn't it enough to just implement AEPWindRose?
